### ISSUE TITLE
list_route plugin

### ISSUE THREAD

**Issue by FatCyclone** [sgabe/docker-scirius#1]
Hello !

After the initial build, i have this error : 

`ImportError: cannot import name 'list_route' from 'rest_framework.decorators' (/usr/local/lib/python3.8/site-packages/rest_framework/decorators.py)
During handling of the above exception, another exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 597, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/scirius/scirius/urls.py", line 6, in <module>
    from .rest_api import router
  File "/opt/scirius/scirius/rest_api.py", line 7, in <module>
    from accounts.rest_api import router as accounts_router
  File "/opt/scirius/accounts/rest_api.py", line 17, in <module>
    from rules.rest_api import CommentSerializer
  File "/opt/scirius/rules/rest_api.py", line 34, in <module>
    from rules.rest_processing import RuleProcessingFilterViewSet
  File "/opt/scirius/rules/rest_processing.py", line 27, in <module>
    from rest_framework.decorators import list_route
ImportError: cannot import name 'list_route' from 'rest_framework.decorators' (/usr/local/lib/python3.8/site-packages/rest_framework/decorators.py)`

Seems that there is a plugin/dependency missing. 
Can you check it out ? It leads to an Internal Server Error.

Thanks !

**Comment by sgabe** [comment]
This should be already fixed by https://github.com/sgabe/scirius/commit/fb5e60bab0965c114404ffc77b5bbcc66941848f. The container pulls Scririus from [this fork](https://github.com/sgabe/scirius) based on `$SOURCE_BRANCH` so rebuilding the container should resolve the issue, see the [build hook](https://github.com/sgabe/docker-scirius/blob/main/hooks/build) for example.

**Comment by FatCyclone** [comment]
Idk, I was using the latest image (When I was talking about build, it's about django first start, when he's constructing assets and etc..  Sorry for the misunderstanding)

**Comment by FatCyclone** [comment]
With your image update, the django stage is passed but after the container init, i have a bad request (400).
I'm investigating. (The environment variable ALLOWED_HOSTS is set)

**Comment by FatCyclone** [comment]
Alright. The environment variables are not set in local_settings.py even if they're set in docker.

**Comment by sgabe** [comment]
I cannot reproduce the issue. Environment variables are passed to the container and picked up by Django as expected. Note that the error message for `DisallowedHost` exception mentions the value of the `Host` header that you may need to add to `ALLOWED_HOSTS`.

**Comment by FatCyclone** [comment]
I'll retry it. Do I need some particular syntax into your container environment variables? Like '' or other special characters ?

**Comment by FatCyclone** [comment]
Managed to get it work (In my compose file, some variables needed to be locked), however, the css is broken ahahah

![image](https://user-images.githubusercontent.com/18697868/104488960-5f46d180-55cf-11eb-85e4-4c997a81f147.png)

**Comment by FatCyclone** [comment]
Something is wrong here :/ (I'm inside the container)

![image](https://user-images.githubusercontent.com/18697868/104490303-fbbda380-55d0-11eb-85bc-90826b69cb2c.png)

**Comment by sgabe** [comment]
You may also have to set `STATIC_ROOT`. It seems that there is something wrong with the `local_settings.py` as you mentioned in https://github.com/sgabe/docker-scirius/issues/1#issuecomment-759485580. The [local_settings.py](https://github.com/sgabe/docker-scirius/blob/main/scirius/scirius/local_settings.py) should be in the `/opt/scirius/scirius` folder. Are you using a bind mount for `/static`?

**Comment by FatCyclone** [comment]
I'll check that. Yes I have directory mounted to /static. (Taken from your example)

**Comment by FatCyclone** [comment]
Tried to set everything up but none of the js and css is loading :/

**Comment by FatCyclone** [comment]
Alright, my reverse is not serving static, I found the problem. Thanks you for your help :)
